# Generated by Django 3.1.2 on 2020-10-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
