# Generated by Django 3.1.2 on 2020-10-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201021_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='image',
        ),
    ]
