# Generated by Django 3.1.2 on 2020-10-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201021_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='description',
            field=models.TextField(),
        ),
    ]
